import Head from 'next/head'
import Header from './components/Header'
import Login from './components/Login'
import SideBar from './components/SideBar'
export default function Home({session}) {

  
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className="flex">
        {/* Sidebar */}
        <SideBar />
        {/* Feed */}
        {/* Widget */}        
      </main>
    </div>
  )
}

export async function getServerSideFront(context){
  const session = await getSession(context)
  return {
    props: {
      session
    }
  }
}